name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Update Aptitude cache
      run: sudo apt update

    - name: Install MySQL server
      run: sudo apt install -y mysql-server

    - name: Start MySQL server
      run: sudo mysql.server start

    - name: Configure MySQL server
      run: mysql -proot -uroot -e "GRANT ALL PRIVILEGES ON db_holycraap.* TO 'root'@'localhost'; FLUSH PRIVILEGES"

    - name: Update MySQL client configuration
      run: sed -Ei 's/spring.datasource.(username|password) *=.*/spring.datasource.\1=root/g' src/main/resources/application.properties

    - name: Build with Gradle
      run: gradle build
